frame_id: world
inter_waypoint_delay: 1.0
retry_delay: 2.0
max_retries: 0
waypoints:
  - name: waypoint_1
    x: -10.0
    y: 0.0
    z: 3.0
    yaw_deg: 0.0
  - name: waypoint_2
    x: -10.0
    y: 10.0
    z: 3.0
    yaw_deg: 0.0
  - name: waypoint_3
    x: -10.0
    y: 20.0
    z: 3.0
    yaw_deg: 0.0
