straight_line_global_planner:
  ros__parameters:
    use_sim_time: true
    odometry_topic: /rmf/odom
    goal_topic: /goal_pose
    path_topic: /gbplanner_path
    frame_id: map
    segment_length: 1.0
    retrigger_distance: 1.0
