reference_velocity_commander:
  ros__parameters:
    # Interfaces
    waypoint_topic: /move_base_simple/goal           # geometry_msgs/PoseStamped
    odometry_topic: /rmf/odom                        # nav_msgs/Odometry
    obstacle_topic: /rmf/lidar/points_downsampled   # sensor_msgs/PointCloud2
    ref_vel_topic: /rmf/ref_vel                      # std_msgs/Float32

    publish_rate: 20.0                   # Hz

    # Obstacle speed interpolation
    min_distance_obstacle: 20.0          # m: at/below this, use min speed
    max_distance_obstacle: 30.0          # m: at/above this, use max speed
    min_speed_obstacle: 2.0              # m/s
    max_speed_obstacle: 4.0              # m/s

    # Waypoint speed interpolation
    min_distance_waypoint: 2.0           # m: at/below this, use min speed
    max_distance_waypoint: 10.0          # m: at/above this, use max speed
    min_speed_waypoint: 1.0              # m/s
    max_speed_waypoint: 4.0              # m/s
