use_gbplanner_selector:
  ros__parameters:
    use_sim_time: true
    input_topic: /rmf/lidar/points_downsampled
    output_topic: /use_gbplanner
    enable_use_gbplanner_selector: false
    distance_threshold_enable_gbplanner: 18.0
    distance_threshold_enable_gbplanner_urgent: 14.0 # Bypass duration_threshold and enable GBPlanner immediately inside this radius.
    distance_threshold_disable_gbplanner: 20.0
    duration_threshold: 1.0 # duration distance thrshold must be satisfied before switching use_gbplanner boolean
